controllers:
    resource: ../src/Controller/
    type: attribute
HelloController:
    path: /bonjour
    controller : App\Controller\HelloController::sayHello
HelloControllerName:
    path: /bonjour/{name}
    controller : App\Controller\HelloController::sayHelloUtil
